version: '3.9'
services:
  meinfahrer-be:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/app/src
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./local/postgres:/var/lib/postgresql/data