version: '3.9'
services:
  meinfahrer-be:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/app/src
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./local/postgres:/var/lib/postgresql/data
volumes:
  yarn-cache: